import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/welcome-page.module.css';

export default function WelcomePage({ welcomePageData }: any) {
  const siteName: string = 'WINGMAN';

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <Link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='plano-wlc-page-wrapper' id='welcome-page'>
        <div className='plano-wlc-page-container'>
          <div className='plano-wlc-page-content'>
            <div className='plano-bull-logo-cont'>
              <img
                width='50'
                height='50'
                alt='Red Bull'
                src={welcomePageData.image}
              />
            </div>
            <div className='plano-wing-titles-cont'>
              <span className='wingman-title'>{siteName}</span>
              <br />
              {welcomePageData.welcomeProgram}
              {/* {'welcomeProgram' | CustomTranslation:langSelected} {year} */}
            </div>
            <div
              className='wlc-page-countries-cont countries-list'
              id='country-list'
            >
              <div className='country-cont'>
                <div className='country-content {{country.toLowerCase()}}'>
                  {welcomePageData.countries.map((country: string) => (
                    <div>{country}</div>
                  ))}
                </div>
              </div>
              <div className='select-country'>
                {'{'}
                {'{'}'welcomeSelectACountryToStart' |
                CustomTranslation:langSelected
                {'}'}
                {'}'}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`http://localhost:3000/api/welcome-page`);
  const welcomePageData = await res.json();
  return {
    props: {
      welcomePageData: welcomePageData,
    },
  };
};
