import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/sub-categories.module.css';
import React, { useState, useEffect } from 'react';

//For the accordion
import Accordion from '@mui/material/Accordion';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { style } from '@mui/system';
import { ClassNames } from '@emotion/react';
import { useRouter } from 'next/router';
import ISO6391 from 'iso-639-1';
import Footer from '../../components/Footer';

export default function SubCategories({
  commonData,
  subCategoriesPageData,
}: any) {
  const router = useRouter();
  let langSelected: any = '';
  let subCategories: any = [];
  const [renderSubCategories, setRenderSubCategories] = useState([]);

  const [expanded, setExpanded] = useState<string | false>(false);
  //Animation Disable Variables
  const [animationsEnabled, enableAnimations] = React.useState(false);
  const stylesheetRef = React.useRef<HTMLStyleElement>();
  //Animation Disable Variables

  const handleChange =
    (panel: string) => (event: React.SyntheticEvent, isExpanded: boolean) => {
      setExpanded(isExpanded ? panel : false);
    };

  function getAndSetLanguage(langSelected: any) {
    langSelected = localStorage.getItem('language');
    if (langSelected === null || undefined)
      langSelected = ISO6391.getName(window.navigator.language.substring(0, 2));
    else if (langSelected === null || undefined) langSelected = 'english';
    return langSelected.toLowerCase();
  }

  function getMethod(mainContent: any, countryChosen: any): void {
    mainContent = mainContent.filter(
      (data: any): boolean =>
        data.country.toLowerCase() === countryChosen.toLowerCase()
    );
    mainContent.map((item: any) => (mainContent = item.content));
    return mainContent;
  }

  useEffect(() => {
    langSelected = getAndSetLanguage(langSelected);
    subCategories = getMethod(subCategoriesPageData.subCategories, 'lebanon');
    setRenderSubCategories(subCategories);
  }, []);

  //Animation Disable Hook
  React.useEffect(() => {
    if (!stylesheetRef.current) {
      stylesheetRef.current = document.createElement('style');
      document.head.appendChild(stylesheetRef.current);
    }

    if (animationsEnabled) {
      const sheet = stylesheetRef.current.sheet;
      if (sheet?.cssRules.length) {
        sheet.deleteRule(0);
      }
    } else {
      const sheet = stylesheetRef.current.sheet;
      const styles = `*,
        *::before,
        *::after {
          transition: none !important;
          animation: none !important;
        }`;
      sheet!.insertRule(styles, 0);
    }
  }, [animationsEnabled]);
  //Animation Disable Hook

  function navigateInsightsPage(): void {
    router.push('/insights');
  }

  function navigateVipPage(): void {
    router.push('/vip');
  }

  function navigateInnerPage(): void {
    router.push('/inner-page');
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <Link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='sub-categories-wrapper'>
        <div className='fxd-header-sect-cont sub-categories'>
          <div className='fxd-header-sect'>
            <div className='fxd-header-content'>
              {/* {subCategoryName | CustomTranslation:langSelected} */}{' '}
              {subCategoriesPageData.subCategoryName}
            </div>
            <div
              onClick={() => {
                navigateInnerPage();
              }}
            >
              <svg
                xmlns='http://www.w3.org/2000/svg'
                width='18.613'
                height='14.083'
                viewBox='0 0 18.613 14.083'
              >
                <path
                  className='a'
                  d='M2.814,21.877l6,6A1.039,1.039,0,1,0,10.279,26.4L6.066,22.17H20.075a1.039,1.039,0,1,0,0-2.077H6.066l4.212-4.212a1.028,1.028,0,0,0,0-1.469,1.07,1.07,0,0,0-.745-.314,1.024,1.024,0,0,0-.745.314L2.814,20.387a1.04,1.04,0,0,0,0,1.489Z'
                  transform='translate(21.113 28.181) rotate(180)'
                />
              </svg>
            </div>
          </div>
        </div>
        {/* //Keep this for now */}
        <div className={styles.headerPaddingDiv}></div>
        <div>
          {renderSubCategories.map((subCategory: any, index: any) => {
            return (
              <div key={index} className='general-small-padding'>
                <Accordion
                  expanded={expanded === subCategory.id}
                  onChange={handleChange(subCategory.id)}
                >
                  <AccordionSummary
                    expandIcon={<ExpandMoreIcon />}
                    aria-controls='panel1bh-content'
                    id='panel1bh-header'
                  >
                    <div>
                      <div className='sub-categories-content'>
                        {/* {subCategory.title | CustomTranslation:langSelected} {subCategory.subTitle | CustomTranslation:langSelected} */}
                        <div className={styles.subCatsTitle}>
                          {/* {{subCategory.title | CustomTranslation:langSelected}} */}
                          {subCategory.title}
                        </div>
                        <div className={styles.subCatSubTitle}>
                          {/* {{subCategory.subTitle | CustomTranslation:langSelected}} */}
                          {subCategory.subTitle}
                        </div>
                      </div>
                    </div>
                  </AccordionSummary>
                  <AccordionDetails className={styles.subCategoryContainer}>
                    <div className='sub-categories-container'>
                      <div className='sub-categories-content'>
                        <div className='sub-cats-inner-page-cont'>
                          <div className='sub-cats-inner-page'>
                            <div className='sub-cats-inner-page-title'>
                              {/* {subCategory.nestedDetails.title |
                  CustomTranslation:langSelected} */}{' '}
                              {subCategory.nestedDetails.title}
                            </div>
                            <div className='sub-cats-inner-page-img'>
                              <Image
                                src={subCategory.nestedDetails.imagePath}
                                alt='{{subCategory'
                              />
                            </div>
                            <div className='sub-cats-inner-page-flow'>
                              {/* {subCategory.nestedDetails.flow |
                  CustomTranslation:langSelected } */}{' '}
                              {subCategory.nestedDetails.flow}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </AccordionDetails>
                </Accordion>
              </div>
            );
          })}
        </div>

        <Footer commonData={commonData} />
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const commonRes = await fetch(
    `${
      process.env.NODE_ENV !== 'production'
        ? 'http://localhost:3000/api/common-data'
        : ''
    }`
  );

  const replaceWithApiOne = {
    siteName: 'WINGMAN',
    welcomeProgram: 'program 2022',
    discover: 'Discover',
    vip: 'VIP',
    insights: 'INSIGHTS',
  };

  const commonData = await commonRes.json();

  const res = await fetch(
    `${
      process.env.NODE_ENV !== 'production'
        ? 'http://localhost:3000/api/sub-categories'
        : ''
    }`
  );

  const replaceWithApiTwo = {
    subCategoryName: 'impulse',
    subCategories: [
      {
        country: 'Lebanon',
        content: [
          {
            id: 1,
            title: 'impulseA',
            subTitle: 'shelfMainPlacement',
            nestedDetails: {
              title: 'MinTwelveFacings',
              imagePath: '/assets/subCategory/1.png',
              flow: 'TrafficFlow',
              isEmptyContent: false,
            },
          },
          {
            id: 2,
            title: 'impulseB',
            subTitle: 'shelfMainPlacement',
            nestedDetails: {
              title: 'MinTwelveFacings',
              imagePath: '/assets/subCategory/1.png',
              flow: 'TrafficFlow',
              isEmptyContent: false,
            },
          },
          {
            id: 3,
            title: 'impulseC',
            subTitle: 'shelfMainPlacement',
            nestedDetails: {
              title: 'MinTwelveFacings',
              imagePath: '/assets/subCategory/1.png',
              flow: 'TrafficFlow',
              isEmptyContent: false,
            },
          },
        ],
      },
      {
        country: 'Qatar',
        content: [
          {
            id: 1,
            title: 'Impulse A',
            subTitle: 'shelfMainPlacement',
            nestedDetails: {
              title: 'MinTwelveFacings',
              imagePath: '/assets/subCategory/1.png',
              flow: 'TrafficFlow',
              isEmptyContent: false,
            },
          },
          {
            id: 2,
            title: 'impulseB',
            subTitle: 'shelfMainPlacement',
            nestedDetails: {
              title: 'MinTwelveFacings',
              imagePath: '/assets/subCategory/1.png',
              flow: 'TrafficFlow',
              isEmptyContent: false,
            },
          },
        ],
      },
    ],
  };

  const subCategoriesPageData = `${
    process.env.NODE_ENV !== 'production' ? await res.json() : replaceWithApiTwo
  }`;

  return {
    props: {
      subCategoriesPageData: subCategoriesPageData,
      commonData: commonData,
    },
  };
};
