import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/languages.module.css';

export default function Languages({ articles }: any) {
  console.log(articles);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <Link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta httpEquiv='X-UA-Compatible' content='ie=edge' />
        <link rel='stylesheet' href='stylesheet.css' />
        <title>Document</title>
        <div className='plano-wlc-page-wrapper' id='welcome-page'>
          <div className='plano-wlc-page-container'>
            <div className='plano-wlc-page-content'>
              <div className='plano-bull-logo-cont'>
                <img src='assets/logo.png' alt='Red Bull' />
              </div>
              <div className='plano-wing-titles-cont'>
                <span className='wingman-title'>wingman</span> <br />
                program 2021
              </div>
              {/*    <div class="wlc-page-countries-cont countries-list" id="country-list" style="display: none;">
                  <div class="country-cont" onclick="elio()">
                      <div class="country-content uae">
                          UAE
                      </div>
                  </div>
                  <div class="country-cont" onclick="elio()">
                      <div class="country-content maldives">
                          Maldives
                      </div>
                  </div>
                  <div class="country-cont" onclick="elio()">
                      <div class="country-content pak">
                          Pakistan
                      </div>
                  </div>
                  <div class="select-country">
                      Select country to start
                  </div>
              </div>*/}
              <div
                className='wlc-page-countries-cont language-menu'
                id='lang-list'
                style={{}}
              >
                <div className='country-cont lang' onclick='innerPlanogram()'>
                  <div className='country-content languages'>English</div>
                </div>
                <div className='country-cont lang' onclick='innerPlanogram()'>
                  <div className='country-content languages'>Urdu</div>
                </div>
                <div className='country-cont lang' onclick='innerPlanogram()'>
                  <div className='country-content languages'>Arabic</div>
                </div>
                <div className='select-country'>
                  Select language from above to start
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const articles = await res.json();
  return {
    props: {
      articles: articles,
    },
  };
};
